# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('port', models.IntegerField()),
                ('users', models.ManyToManyField(to='resource_manager.CustomUser')),
            ],
        ),
    ]
