# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0006_auto_20170306_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='ip',
            new_name='private_ip',
        ),
        migrations.RemoveField(
            model_name='node',
            name='port',
        ),
        migrations.AlterField(
            model_name='node',
            name='users',
            field=models.ManyToManyField(blank=True, max_length=4, to='resource_manager.models.JupyterUser'),
        ),
    ]
