# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0007_auto_20170306_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='users',
        ),
        migrations.AddField(
            model_name='customuser',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resource_manager.Node'),
            preserve_default=False,
        ),
    ]
