# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0010_auto_20170306_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='JupyterUser',
        ),
    ]
