# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0012_auto_20170306_2148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jupyteruser',
            unique_together=set([('node', 'port')]),
        ),
    ]
