# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0013_auto_20170306_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupyteruser',
            name='port',
            field=models.CharField(choices=[('50001', '50001'), ('50002', '50002'), ('50003', '50003'), ('50004', '50004')], default='50001', max_length=5),
        ),
    ]
