# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0015_auto_20170306_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupyteruser',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_manager.Node'),
        ),
    ]
