# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0017_auto_20170306_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jupyteruser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jupyteruser',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='jupyteruser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jupyteruser',
            name='port',
            field=models.CharField(blank=True, choices=[('50001', '50001'), ('50002', '50002'), ('50003', '50003'), ('50004', '50004'), ('50005', '50005'), ('50006', '50006'), ('50007', '50007')], max_length=5, null=True),
        ),
    ]
