# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_manager', '0018_auto_20170307_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ec2_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='private_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.RemoveField(
            model_name='node',
            name='uuid',
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('private_ip', 'ec2_id')]),
        ),
    ]
